# Generated by Django 2.0.5 on 2018-05-12 12:57

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberOfSeats', models.CharField(max_length=20)),
                ('BusName', models.CharField(max_length=20)),
                ('BusNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(help_text='Enter Email', max_length=50)),
                ('Password', models.CharField(help_text='Enter Password', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(help_text='Enter Firstname', max_length=50)),
                ('LastName', models.CharField(help_text='Enter Lastname', max_length=50)),
                ('Email', models.EmailField(help_text='Enter email address', max_length=50)),
                ('PhoneNumber', models.CharField(help_text='Phone number', max_length=25)),
                ('Password', models.CharField(help_text='Input Password', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TravelList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pickup_Point', models.CharField(max_length=50)),
                ('Day', models.CharField(max_length=30)),
                ('Time', models.TimeField()),
                ('Destination', models.CharField(max_length=50)),
            ],
        ),
    ]
